[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm run start-simple"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[services]
  [services.web]
    sourceDir = "/"
    startCommand = "npm run start-simple"
    healthcheckPath = "/api/health"
    healthcheckTimeout = 100
    restartPolicyType = "ON_FAILURE"
    restartPolicyMaxRetries = 10

  [services.mysql]
    sourceDir = "/"
    image = "mysql:8.0"
    healthcheckPath = "/health"
    healthcheckTimeout = 100
    restartPolicyType = "ON_FAILURE"
    restartPolicyMaxRetries = 10
