services:
  # Service Backend Node.js
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: sql103.infinityfree.com
      - key: DB_USER
        value: if0_38348735
      - key: DB_PASS
        value: vGBFeP3qyT
      - key: DB_NAME
        value: if0_38348735_gestion_formations
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        value: votre_secret_jwt_tres_securise_ici
      - key: FRONTEND_URL
        value: https://votre-frontend-url.onrender.com
